[project]
name = 'Autonomous-Shipping-Network'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.cargo]
path = 'contracts/cargo.clar'
clarity_version = 2
epoch = 2.5

[contracts.route-optimization]
path = 'contracts/route-optimization.clar'
clarity_version = 2
epoch = 2.5

[contracts.vessel-registration]
path = 'contracts/vessel-registration.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
